"""The store's public surface, pinned and demonstrated.

DO NOT EDIT THIS FILE.
"""

import inspect
import sqlite3

import pytest
from pydantic import BaseModel

from app.models import BiomarkerDefinition, Member, ResultsDocument
from app.store import Store

PUBLIC = {"get", "query", "keys", "scan", "put", "put_many", "delete", "close"}

SCRATCH = "scratch:demo"


class Note(BaseModel):
    text: str
    n: int = 0


def test_public_surface_is_unchanged():
    actual = {
        name
        for name, _ in inspect.getmembers(Store, callable)
        if not name.startswith("_")
    }
    assert actual == PUBLIC, (
        f"added: {sorted(actual - PUBLIC)}  removed: {sorted(PUBLIC - actual)}"
    )


# ----------------------------------------------------------------- get


def test_get_returns_the_document_at_a_key_pair(store):
    member = store.get("user", "user-1", Member)
    assert member.email == "james.chen@example.com"


def test_get_returns_none_when_nothing_is_there(store):
    assert store.get("user", "nobody", Member) is None
    assert store.get("no-such-partition", "user-1", Member) is None


def test_get_is_typed_or_not_as_you_choose(store):
    assert isinstance(store.get("user", "user-1", Member), Member)
    assert isinstance(store.get("user", "user-1"), dict)


# --------------------------------------------------------------- query


def test_query_returns_a_partition_in_sort_key_order(store):
    draws = list(store.query("results:user-1", ResultsDocument))
    assert len(draws) == 5
    assert [sort_key for sort_key, _ in draws] == sorted(
        sort_key for sort_key, _ in draws
    )
    assert all(draw.user_id == "user-1" for _sk, draw in draws)


def test_query_does_not_cross_partitions(store):
    for _sk, draw in store.query("results:user-2", ResultsDocument):
        assert draw.user_id == "user-2"


def test_query_yields_rather_than_building_a_list(store):
    assert inspect.isgenerator(store.query("biomarker", BiomarkerDefinition))


def test_query_bounds_are_start_inclusive_end_exclusive(store):
    every = [sort_key for sort_key, _ in store.query("results:user-1")]
    first, second, third = every[:3]

    assert [k for k, _ in store.query("results:user-1", start=second)] == every[1:]
    assert [k for k, _ in store.query("results:user-1", end=third)] == [first, second]
    assert [k for k, _ in store.query("results:user-1", start=second, end=third)] == [
        second
    ]


def test_query_on_an_unknown_partition_is_empty_not_an_error(store):
    assert list(store.query("nothing-here")) == []


# ---------------------------------------------------------------- keys


def test_keys_yields_sort_keys_only(store):
    sort_keys = list(store.keys("user"))
    assert sort_keys == ["user-1", "user-2", "user-3", "user-4"]


def test_keys_takes_the_same_bounds_as_query(store):
    every = list(store.keys("results:user-1"))
    assert list(store.keys("results:user-1", start=every[1])) == every[1:]


# ---------------------------------------------------------------- scan


def test_scan_crosses_partitions_and_yields_the_partition_key(store):
    seen = {pk for pk, _sk, _doc in store.scan("results:")}
    assert {
        "results:user-1",
        "results:user-2",
        "results:user-3",
        "results:user-4",
    } <= seen


def test_scan_with_no_prefix_walks_everything(store):
    partitions = {pk for pk, _sk, _doc in store.scan()}
    assert {"user", "email", "biomarker"} <= partitions


def test_scan_is_typed_or_not_as_you_choose(store):
    _pk, _sk, typed = next(iter(store.scan("results:", ResultsDocument)))
    _pk, _sk, raw = next(iter(store.scan("results:")))
    assert isinstance(typed, ResultsDocument)
    assert isinstance(raw, dict)


# ----------------------------------------------------------- put, delete


def test_put_then_get_round_trips(store):
    store.put(SCRATCH, "a", Note(text="hello", n=1))
    assert store.get(SCRATCH, "a", Note) == Note(text="hello", n=1)


def test_put_accepts_a_plain_dict(store):
    store.put(SCRATCH, "b", {"text": "from a dict", "n": 2})
    assert store.get(SCRATCH, "b", Note).text == "from a dict"


def test_put_overwrites_the_same_key_pair(store):
    store.put(SCRATCH, "a", Note(text="first"))
    store.put(SCRATCH, "a", Note(text="second"))
    assert store.get(SCRATCH, "a", Note).text == "second"
    assert len(list(store.keys(SCRATCH))) == 1


def test_the_same_sort_key_in_two_partitions_is_two_documents(store):
    store.put(SCRATCH, "shared", Note(text="here"))
    store.put("scratch:other", "shared", Note(text="there"))
    assert store.get(SCRATCH, "shared", Note).text == "here"
    assert store.get("scratch:other", "shared", Note).text == "there"


def test_put_many_writes_a_batch_and_returns_the_count(store):
    written = store.put_many(
        [(SCRATCH, f"{i:02d}", Note(text="batch", n=i)) for i in range(5)]
    )
    assert written == 5
    assert [sort_key for sort_key, _ in store.query(SCRATCH)] == [
        "00",
        "01",
        "02",
        "03",
        "04",
    ]


def test_put_many_spans_partitions(store):
    store.put_many(
        [
            (SCRATCH, "x", Note(text="one")),
            ("scratch:other", "y", Note(text="two")),
        ]
    )
    assert store.get(SCRATCH, "x", Note).text == "one"
    assert store.get("scratch:other", "y", Note).text == "two"


def test_delete_removes_one_document_and_leaves_the_rest(store):
    store.put_many([(SCRATCH, "a", Note(text="a")), (SCRATCH, "b", Note(text="b"))])
    store.delete(SCRATCH, "a")
    assert store.get(SCRATCH, "a", Note) is None
    assert [sort_key for sort_key, _ in store.query(SCRATCH)] == ["b"]


def test_delete_of_something_absent_is_not_an_error(store):
    store.delete(SCRATCH, "never-existed")


# --------------------------------------------------------------- close


def test_close_releases_the_connection(db_path):
    store = Store(db_path)
    assert store.get("user", "user-1", Member) is not None
    store.close()
    with pytest.raises(sqlite3.ProgrammingError):
        store.get("user", "user-1", Member)
